#Roger Verzola Peres de Lima 1693271
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(609, 459)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 254, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout.addWidget(self.pushButton_15)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(30, 40, 541, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(260, 10, 221, 171))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout.addWidget(self.pushButton_13)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 218, 172))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_52 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_52.setObjectName("pushButton_52")
        self.verticalLayout_7.addWidget(self.pushButton_52)
        self.pushButton_53 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_53.setObjectName("pushButton_53")
        self.verticalLayout_7.addWidget(self.pushButton_53)
        self.pushButton_54 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_54.setObjectName("pushButton_54")
        self.verticalLayout_7.addWidget(self.pushButton_54)
        self.pushButton_55 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_55.setObjectName("pushButton_55")
        self.verticalLayout_7.addWidget(self.pushButton_55)
        self.pushButton_56 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_56.setObjectName("pushButton_56")
        self.verticalLayout_7.addWidget(self.pushButton_56)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(290, 10, 211, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_68 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_68.setObjectName("pushButton_68")
        self.verticalLayout_10.addWidget(self.pushButton_68)
        self.pushButton_71 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_71.setObjectName("pushButton_71")
        self.verticalLayout_10.addWidget(self.pushButton_71)
        self.pushButton_67 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_67.setObjectName("pushButton_67")
        self.verticalLayout_10.addWidget(self.pushButton_67)
        self.pushButton_70 = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.pushButton_70.setObjectName("pushButton_70")
        self.verticalLayout_10.addWidget(self.pushButton_70)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Carregar imagem"))
        self.pushButton_14.setText(_translate("Form", "Cinza"))
        self.pushButton_15.setText(_translate("Form", "HSV"))
        self.pushButton_8.setText(_translate("Form", "Filtro da Media"))
        self.pushButton_9.setText(_translate("Form", "Filtro da Mediana"))
        self.pushButton_10.setText(_translate("Form", "Filtro do Minimo"))
        self.pushButton_11.setText(_translate("Form", "Filtro do Maximo"))
        self.pushButton_12.setText(_translate("Form", "Filtro Gaussiano"))
        self.pushButton_13.setText(_translate("Form", "Filtro Laplaciano"))
        self.pushButton_2.setText(_translate("Form", "Negativo"))
        self.pushButton_3.setText(_translate("Form", "Logaritmica"))
        self.pushButton_4.setText(_translate("Form", "Potencia"))
        self.pushButton_5.setText(_translate("Form", "Histograma"))
        self.pushButton_7.setText(_translate("Form", "Histograma Equalizado"))
        self.pushButton_6.setText(_translate("Form", "Ajuste de contraste"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.pushButton_52.setText(_translate("Form", "Limiarizacao Manual"))
        self.pushButton_53.setText(_translate("Form", "Limiarizacao Otsu"))
        self.pushButton_54.setText(_translate("Form", "Crescimento de Regioes"))
        self.pushButton_55.setText(_translate("Form", "Deteccao De Bordas Sobel"))
        self.pushButton_56.setText(_translate("Form", "Deteccao de Bordas Canny"))
        self.pushButton_68.setText(_translate("Form", "Abertura da Ultima Segmentação"))
        self.pushButton_71.setText(_translate("Form", "Fechamento da Ultima Segmentação"))
        self.pushButton_67.setText(_translate("Form", "BIC"))
        self.pushButton_70.setText(_translate("Form", "Código da Cadeia"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))

